name: Build & Scan

on:
  schedule:
    # Build the image once a day to ensure security updates
    # are recent & the build continues to pass.
    - cron: '0 0 * * *'

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  IMAGE_TAGS: |
    ghcr.io/${{ github.repository_owner }}/flocker:latest
    ghcr.io/${{ github.repository_owner }}/flocker:${{ github.sha }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_TAGS }}

      - name: Run Anchore scan with GitHub Advanced Security code scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ghcr.io/${{ github.repository_owner }}/flocker:${{ github.sha }}
          acs-report-enable: true
          fail-build: false
          severity-cutoff: critical

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
